## 아이템 13 - clone 재정의는 주의해서 진행하라 - 완벽 공략
---

### UncheckedException

우리는 보통 UncheckedException 을 선호햔다.

```java
public class MyException extends RuntimeException {
}
```

UncheckedException 은 __RuntimeException 을 상속__ 받은 Exception 이다.

```java
public class MyException extends Error {
}
```

__Error__ 를 상속받은 클래스들 역시 __UncheckedException__ 이라고 부를 수 있다.

__RuntimeException__ 과 __Error__ 를 확장한 클래스들은 __UncheckedException__ 이다.

우리는 왜 UncheckedException 을 선호할까?

```java
public class MyApp {

   public void hello(String name)  {
      throw new MyException();
   }

   public static void main(String[] args) {
      MyApp myApp = new MyApp();
      myApp.hello("junhyun");
   }
}
```

__UncheckedException__ 던지는 코드는 작성이 쉽다.

호출을 하더라도 사용하는 쪽에서 조치를 할 필요가 없다.

만약 __CheckedException__ 이라면

```java
public class MyException extends Exception {
}
```
```java
public class MyApp {

   public void hello(String name)  {
      throw new MyException();
   }

   public static void main(String[] args) {
      MyApp myApp = new MyApp();
      try {
         myApp.hello("푸틴");
      } catch (MyException e) {
         e.printStackTrace();
      }
   }
}
```
해당 코드를 호출하는 쪽에서 ``try-catch`` 블럭을 사용하거나

```java
   public void hello(String name) throws MyException {
      throw new MyException();
   }
```
``throws`` 를 사용해 에러를 던져야한다.

만약 ``throws`` 를 하게되면 해당 코드를 받는 쪽에서 다시한번 처리를 해주어야한다.

이러한 번거로움 떄문에 __UncheckedException__ 을 선호하게 된다.

하지만 이러한 이유만으로 __UncheckedException__ 사용을 결정하는 건 잘못된 선택이다.

절대 편리하다는 이유만으로 __UncheckedException__ 을 사용하면 안된다.

__CheckedException__ 의 ``try-catch`` 나 ``throws`` 가 있는 이유는

__CheckedException__ 자체만으로 API 이기 떄문이다.

클라이언트에게 해당 메서드 호출 시 __CheckedException__ 이 발생할 수 있음을 알려준다.

```java
public class MyApp {

   /**
    *
    * @param name
    * @throws MyException
    */
   public void hello(String name) throws MyException {
      if (name.equals("푸틴")) {
         throw new MyException();
      }

      System.out.println("hello");
   }

   public static void main(String[] args) {
      MyApp myApp = new MyApp();
      try {
         myApp.hello("푸틴");
      } catch (MyException e) {
         e.printStackTrace();
      }
   }
}
```
위의 코드는 잘못된 값이 들어왔을 떄 예외를 던지게 된다.

잘못된 값이 들어오면 코드를 사용하는 쪽에서 대응을 할 수 있다.

무언가 복구를 하는 시도를 할 수 있도록 API 를 사용하는 쪽에 정보를 제공한다.

이떄 __CheckedException__ 은 __문서화__ 가 되어 있어야한다.

```java
public class MyApp {

   /**
    *
    * @param name
    * @throws MyException
    */
   public void hello(String name) throws MyException, NullPointerException {
      if (name.equals("푸틴")) {
         throw new MyException();
      }

      System.out.println("hello");
   }

   public static void main(String[] args) {
      MyApp myApp = new MyApp();
      try {
         myApp.hello("푸틴");
      } catch (MyException e) {
         e.printStackTrace();
      }
   }
}
```
위의 코드와 같이 __UncheckedException__ 계열의 예외 역시 ``try-catch`` 나 ``throws`` 를 사용할 수 있다.

하지만 __UncheckedException__ 은 복구할 수 있는 방법이 없기 때문에 ``try-catch`` 나 ``throws`` 를 __강제__ 하지 않는다.

__UncheckedException__ 은 언제 어디서든 발생할 수 있기 때문에 ``try-catch`` 나 ``throws`` 를 사용하면 

비효율적인 동시에 프로그램의 명확도를 떨어뜨린다.

클라이언트 코드에서 해당 예외를 __복구할 수 있는 방법__ 이 있다면 __CheckedException__ 을 사용하도록 하자.

---

### TreeSet


